### PR TITLE
Add linkable line numbers to files via Prismjs

### PR DESCRIPTION
**Pull request by cainwatson**
Ticket: #15

### Line numbers

http://localhost:4005/preview/decimal/2.0.0/lib%2Fdecimal%2Ferror.ex:

### Linkable

Clicking a line number adds the line number prepended with `L.` to the url hash, e.g. `...README.md#L.9`. Open refresh/revisiting site with the hash, the line number continues to be focused and highlighted.

http://localhost:4005/preview/decimal/2.0.0/README.md#L.9:

## Implementation

This was implemented with [PrismJs](https://prismjs.com/plugins) instead of using the existing Makeup library. We may want to stick with Makeup, but here were the challenges and the thought process:
* The current implementation calls `Makeup.highlight` which returns the raw html. In order to add line numbers, I would need to know what code was on each line to then produce html that could display and link each line number. Editing the returned html to determine what represents each line would be quite difficult and error-prone, especially if the html were to change in the future.
* I also tried to split the file itself by new lines and then call `Makeup.highlight` on each line, but this returned unexpected syntax highlighting since a line could be apart of a block of other lines (such as a @doc comment) and Makeup wouldn't know the context of the other lines.
* Reading Makeup's documentation, it seems like it could support a way to easily access each line or edit the returned html to include this, but currently I couldn't find a way to do it
* Given these challenges, I looked for another solution and found Prism. Prism comes out the box with plugins for [line numbers](https://prismjs.com/plugins/line-numbers/) and [line highlighting](https://prismjs.com/plugins/line-highlight/) which made it very quick and easy to implement.

### Afterthoughts

LiveView presented some hurdles with Prism. These may just have been challenging for me because of my lack of experience with LiveView, or just because it doesn't play nice. These issues include:
* Prism js automatically detects the html on the page to hightlight (via css classes) and does the highlighting for you. This would work on initial page load, but after live view pushed updates to the view and loaded, the highlighting would disappear. This required an event listener to be added on when the live view finished loading that would re-highlight the code:
  ```js
  window.addEventListener("phx:page-loading-stop", (info) => {
    Prism.highlightAll()
  })
  ```
* I added a phoenix hook to reapply the highlighting when a new file was selected. This would work, then immediately go back to being unhighlighted.
  ```js
  {
    updated() {
      Prism.highlightElement(this.el.firstChild)
    },
  }
  ```
  The fix was to schedule the highlighting to happen after the event was complete via setTimeout:
  ```js
  {
    updated() {
      setTimeout(() => {
        Prism.highlightElement(this.el.firstChild)
      })
    },
  }
  ```
* It feels like sometimes it takes longer for the syntax highlighting to happen. Not sure if it has to do with the highlighting being called multiple times or something else... Prismjs does support an `async` option that would run the highlighting in a web worker, but it's [disabled by default](https://prismjs.com/faq.html#why-is-asynchronous-highlighting-disabled-by-default).
* Currently, the line number linking does not support ranges. So you can't click one line and then shift click 5 lines down to select them all. The line highlight plugin does support the ability to highlight multiple lines, it's just that there's some missing functionality with the linking that could be extended with a custom plugin

Sorry if this seems like a lot of info for a seemingly simple line number feature 😅, but I thought I'd document and explain as much as I could.

### CODE REVIEW

**Review by supersimple — CHANGES_REQUESTED** [review]
Hi @cainwatson !
Thank you for your contribution.
After reviewing it, I do have some thoughts:
1. having line numbers (and making them directly linkable) is a great feature. I definitely want to pursue that.
2. This is a lot of new code (most of which isn't directly related to the adding line numbers.)
3. I would prefer to stay with makeup because it is more universal in the BEAM world. (@davydog187 is working on adding js support AFAIK.)

I am happy (excited) to work with you on taking another approach to this. Ultimately, I don't really want to support prismjs in this project.

Again - thank you very much for the work. 🌮 🌯 🎉

**Comment by cainwatson** [comment]
> Hi @cainwatson !
> Thank you for your contribution.
> After reviewing it, I do have some thoughts:
> 
> 1. having line numbers (and making them directly linkable) is a great feature. I definitely want to pursue that.
> 2. This is a lot of new code (most of which isn't directly related to the adding line numbers.)
> 3. I would prefer to stay with makeup because it is more universal in the BEAM world. (@davydog187 is working on adding js support AFAIK.)
> 
> I am happy (excited) to work with you on taking another approach to this. Ultimately, I don't really want to support prismjs in this project.
> 
> Again - thank you very much for the work. 🌮 🌯 🎉

Got it, makes sense!

I'll try to look more into makeup to see another way to access each line or a way to extend the html to include line numbers. Let me know if you have ideas or tips to do this!

**Comment by supersimple** [comment]
> I'll try to look more into makeup to find another way to access each line or a way to extend the html to include line numbers. Let me know if you have ideas or tips to do this!

@cainwatson I have been looking into this and talked to Jose about this week. If you want to pair on a solution let me know. I'll be working on it tonight and/or tomorrow

**Comment by cainwatson** [comment]
> @cainwatson I have been looking into this and talked to Jose about this week. If you want to pair on a solution let me know. I'll be working on it tonight and/or tomorrow

@supersimple I would love to pair!

**Comment by supersimple** [comment]
> > @cainwatson I have been looking into this and talked to Jose about this week. If you want to pair on a solution let me know. I'll be working on it tonight and/or tomorrow
> 
> @supersimple I would love to pair!

I sent you an email invite.

**Pull request closed without merging**
