### PR TITLE
Highlight source code with Makeup

### PR DESCRIPTION
**Pull request by davydog187**
I had a timely blog post today, https://til.simplebet.io/posts/eeitetzehd-use-makeup-to-display-data-in-your-phoenix-ui and I thought I'd contribute it back to preview.

- [x] Test with other languages
- [x] Only highlights elixir files for now
- [X] Choose a style format, currently "manni"
- [ ] ~~Possibly move the styles to a stylesheet?~~

### CODE REVIEW

**Review by supersimple — COMMENTED** [review]
Thank you. 
Can you show some samples of available styles?
Also, we are using Yarn (now) so we shouldn't have an updated package-lock.json file.

Thanks again

**Comment by davydog187** [comment]
Here are some options

# Tango
Screen Shot 2021-01-26 at 7 37 16 AM

# RainbowDash
Screen Shot 2021-01-26 at 7 37 48 AM

# Pastie
Screen Shot 2021-01-26 at 7 39 05 AM

# Manni
Screen Shot 2021-01-26 at 7 41 03 AM

# Lovelace
Screen Shot 2021-01-26 at 7 41 45 AM

**Comment by davydog187** [comment]
@supersimple I changed it to "manni" for now, but there's probably a better choice. If you want we can cycle through some options together. You can see the various styles offered by Makeup here https://tmbb.github.io/makeup_demo/elixir.html

**Review by supersimple — APPROVED** [review]
Thanks, Dave! Looks pretty now. 💄 💇🏻‍♀️ 🐰 🐈 🌈

**Pull request merged**
