### PR TITLE
Add linkable line numbers to file preview

### PR DESCRIPTION
**Pull request by cainwatson**
Closes: #15
See details from: https://github.com/hexpm/preview/pull/33#event-4566122750

### CODE REVIEW

**Review by supersimple — APPROVED** [review]
Looks great!! 🌮 🌯 🎉

**Comment by ericmj** [comment]
This is great. Thank you!

**Comment by ericmj** [comment]
On my machine it looks like the line height for the line numbers and code is different, causing them to be misaligned:

Screen Shot 2021-04-08 at 12 35 15

**Comment by wojtekmach** [comment]
Same here, it seems there's a small discrepancy that builds up over time:

image

I'm on macOS 11.2.3, Safari 14.0.3

**Comment by supersimple** [comment]
I'll take a look at it today. I tested it on Firefox, but I see this issue in Chrome

**Comment by supersimple** [comment]
ok, i pushed a change to main that fixes the alignment on FF and Chrome on Linux. If you have time, can one of you check it on Mac?

**Comment by wojtekmach** [comment]
Thanks!

It's consistent but it's slightly off, the code is lower by a couple of pixels compared to the line number:

image

I noticed that clicking on the line numbers always puts you at the top of the page, ideally we'd be scrolled down to where the link is placed.

Finally, a small comment about line number link format, I think it would be good to change `#l30` to `#L30` as people coming from GitHub are probably used to the latter.

**Pull request merged**
